task :default 

package_name = 'dummy-package-name'
begin
    require 'hoe'
    Hoe::plugin :compiler
    Hoe::plugin :yard
    
    hoe_spec = Hoe.spec package_name do
        self.version = 'dummy-version'
        self.developer "dummy-author", "dummy-email"
        extra_deps <<
            ['rake', '>= 0']
        
        extra_dev_deps <<
            ["rake-compiler",     ">= 0.8.0"]
    
        summary = 'dummy-brief-desc'
        readme_file = FileList['README*'].first
        description = paragraphs_of(readme_file, 3..5).join("\n\n")

        spec_extras = {
            :required_ruby_version => '>= 1.8.7'
        }

        # Yard setup
        yard_title = name
        yard_markup = :markdown
    end

    task :doc => :yard

rescue LoadError => e
    puts "Extension for '#{package_name}' cannot be build -- loading hoe gem failed: #{e}"
end

