package_name = 'dummy-package-name'
package_name_ext = "#{package_name}_ext"
begin
    require 'hoe'
    Hoe::plugin :compiler
    Hoe::plugin :yard
    
    hoe_spec = Hoe.spec package_name do
        self.version = 'dummy-version'
        self.developer "dummy-author", "dummy-email"
        extra_deps <<
            ['rake', '>= 0']
        
        extra_dev_deps <<
            ["rake-compiler",     ">= 0.8.0"]
    
        summary = 'dummy-brief-desc'
        readme_file = FileList['README*'].first
        description = paragraphs_of(readme_file, 3..5).join("\n\n")

        spec_extras = {
            :required_ruby_version => '>= 1.8.7'
        }

        # Yard setup
        yard_title = name
        yard_markup = :markdown
    end

    Rake.clear_tasks(/^default$/)
    Rake.clear_tasks(/doc/)

    task :default => []
    task :doc => :yard

    # Check if there are files to build the extension
    ext_files = FileList["ext/#{package_name_ext}/*.c*"]
    if not ext_files.empty?
        hoe_spec.spec.extensions = FileList["ext/#{package_name_ext}/extconf.rb"]

        require 'rake/extensiontask'
        Rake::ExtensionTask.new("#{package_name_ext}") do |ext|
            ext.lib_dir = 'lib'
            ext.tmp_dir = 'build'
            ext.source_pattern = "*.{c,cpp}"
        end

        task :default => "compile:#{package_name_ext}"
    end

rescue LoadError => e
    puts "Extension for '#{package_name}' cannot be build -- loading hoe gem failed: #{e}"
end

